.github/workflows/CI.yml
Src/views/Test/RenderEngineTestBase.h
Src/views/Test/TestVwGraphics.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/11)

Correct errors in the CI.yml

---

Src/Generic/UtilSil.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/27)

Throw a useful error message if the normalizer didn't load

---

Src/Common/SimpleRootSite/SimpleRootSite.cs
Src/LexText/Interlinear/RawTextPane.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/50)

LT-20854: Fix baseline tab focus after returning from different area

---

Src/xWorks/LcmWordGenerator.cs

Add support for groups.
Remaining tasks:
Need to add support for indenting when each group is displayed on a new line.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/55)

LT-21771: Word Export – support grouping nodes

---

Build/Localize.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/56)

Update flags for localizing with overcrowdin version 3

---

Build/Installer.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/57)

Minor refactor and fixup in BuildProductBaseMsi target

---

Src/Transforms/Application/FxtM3ParserToToXAmpleGrammar.xsl

Implement the fix given by Andy Black to speed up grammar creation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/63)

LT-21687: Creating the XAmple grammar file is very slow

---

DistFiles/Language Explorer/Export Templates/Discourse/Discourse2XLingPaper.xsl
DistFiles/Language Explorer/Export Templates/Discourse/XLingPaper.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/74)

LT-19859: Update FLEx chart XLingPaper export per Andy Black

---

Build/mkall.targets
Build/nuget-common/packages.config
Src/LexText/Interlinear/InterlinVc.cs

I made includeContext be false in GetBestGuess, which stops it from looking at the previous word.
I also updated the acceptance test in https://jira.sil.org/browse/LT-21728.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/78)

LT-21728: Parse Prioritizer

---

Build/Installer.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/82)

Attempt to rescue the patching from the removed helps file

---

Build/Installer.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/83)

Correct the directory in the patch rescue for the removed Helps file

---

Build/mkall.targets
Build/nuget-common/packages.config
Src/AppForTests.config
Src/Common/FieldWorks/App.config
Src/Paratext8Plugin/ParaText8PluginTests/App.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/87)

Update config files for new icu.net version

---

Src/xWorks/LcmWordGenerator.cs
Src/xWorks/WordStylesGenerator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/85)

Word Export: Add Writing System Abbreviations

---

Src/AssemblyInfoForTests.cs
Src/Common/FwUtils/FwUtilsTests/FwUpdaterTests.cs
Src/Common/FwUtils/VersionInfoProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/93)

Fix LT-21813: Make Updater code handle odd CultureInfo

---

Src/xWorks/LcmWordGenerator.cs
Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
Src/xWorks/xWorksTests/xWorksTests.csproj

* Process the before after content looking for linebreak characters
* Add unit testing class for LcmWordGenerator
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/96)

Fix LT-21674 linebreak issue and add tests

---

Src/xWorks/LinkListener.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/98)

LT-21822: Display Failed Jump dialog after entry deletion

---

Src/xWorks/XhtmlDocView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/100)

LT-21702b: Fix second test of LT-21702

---

DistFiles/Language Explorer/Configuration/Parts/LexSenseParts.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/106)

LT-21788: Display Inflection Features for affixes

---

Src/xWorks/ConfiguredLcmGenerator.cs
Src/xWorks/ILcmContentGenerator.cs
Src/xWorks/LcmJsonGenerator.cs
Src/xWorks/LcmWordGenerator.cs
Src/xWorks/LcmXhtmlGenerator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/107)

Update ILcmContentGenerator methods to add config nodes and reorder args

---

Build/mkall.targets
Build/nuget-common/packages.config
Src/LCMBrowser/LCMBrowserForm.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/111)

Update CommonServiceLocator to stay compatible with latest LCM

---

Src/Common/SimpleRootSite/SimpleRootSite.cs
Src/LexText/Interlinear/RawTextPane.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/115)

LT-20849: Refresh so vertical scrollbar doesn't cover RTL text

---

Src/LexText/ParserUI/ParserListener.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/121)

Fix null pointer reference in SuppressableParseResult

---

Build/mkall.targets
Build/nuget-common/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/122)

Fix LT-21851 - Update to liblcm with the bugfix

---

Src/LexText/ParserCore/ParserReport.cs
Src/LexText/ParserUI/ParserListener.cs
Src/LexText/ParserUI/ParserReportViewModel.cs
Src/LexText/ParserUI/ParserReportsDialog.xaml
Src/LexText/ParserUI/ParserReportsDialog.xaml.cs
Src/LexText/ParserUI/ParserReportsViewModel.cs
Src/LexText/ParserUI/ParserUIStrings.Designer.cs
Src/LexText/ParserUI/ParserUIStrings.resx

* Move buttons from columns to button row at the bottm
* Change button text to clearer options
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/124)

Make some parser tester UX improvements

---

Src/xWorks/xWorksStrings.Designer.cs
Src/xWorks/xWorksStrings.resx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/125)

Fix LT-21824 by changing error message

---

DistFiles/Language Explorer/Configuration/Main.xml
Src/xWorks/FwXWindow.cs

I switch to Phonology and XML files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/134)

Fix LT-21852: Import Phonology command mistakenly suggests SFM file

---

DistFiles/Language Explorer/Configuration/Words/areaConfiguration.xml
Src/LexText/ParserCore/ParserReport.cs
Src/LexText/ParserUI/ParserListener.cs
Src/LexText/ParserUI/ParserReportDialog.xaml
Src/LexText/ParserUI/ParserReportDialog.xaml.cs
Src/LexText/ParserUI/ParserReportViewModel.cs
Src/LexText/ParserUI/ParserReportsDialog.xaml
Src/LexText/ParserUI/ParserUI.csproj
Src/LexText/ParserUI/ParserUIStrings.Designer.cs
Src/LexText/ParserUI/ParserUIStrings.resx
Src/xWorks/LcmWordGenerator.cs

I also fixed the problem reported by Beth.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/131)

LT-21859: Fix minor problems in parser test reports

---

Src/FwCoreDlgs/BasicFindDialog.Designer.cs
Src/FwCoreDlgs/BasicFindDialog.cs
Src/FwCoreDlgs/BasicFindDialog.resx
Src/xWorks/XhtmlDocView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/132)

Fix LT-21701: Add basic find dialog for Dictionary views

---

Src/LexText/ParserUI/ParserReportDialog.xaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/136)

Fix LT-21869: Run Tests report columns don't expand

---

Src/LexText/ParserCore/ParserScheduler.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/135)

Fix LT-21865: Parser hangs on non-primary writing system

---

Build/mkall.targets
Build/nuget-common/packages.config

- Remove one more TeamCity dependency by switching to nuget
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/137)

Start using IPCFramework Nuget package

---

Src/xWorks/ConfiguredLcmGenerator.cs
Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs
Src/xWorks/xWorksTests/CssGeneratorTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/139)

LT-21840: Fix missing before/between/after text and add relevant test

---

Src/Common/Controls/Widgets/PopupTree.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/141)

Enlarge popuptree window (LT-21584)

---

DistFiles/Language Explorer/Export Templates/Phonology.xml
Src/FwResources/FwStrings.Designer.cs
Src/FwResources/FwStrings.resx
Src/FwResources/ResourceHelper.cs
Src/xWorks/FwXWindow.cs

Changes the file types part from XML to Phonology XML in import and export.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/144)

LT-21852: Change the file types part

---

DistFiles/Language Explorer/Configuration/CommonDataTreeInclude.xml
Src/Common/Controls/DetailControls/ButtonLauncher.cs
Src/Common/Controls/DetailControls/DataTree.cs
Src/Common/Controls/DetailControls/Slice.cs
Src/Common/Controls/DetailControls/SliceTreeNode.cs

* Add menu items and first cut at handlers for it
* Also cleaned up some obsolete code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/127)

Add menu items for moving fields up and down in the interface

---

DistFiles/Language Explorer/Configuration/strings-en.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/151)

Fix LT-21909: Add a hyphen in "Remove Parser approved analyses"

---

DistFiles/Language Explorer/Configuration/CommonDataTreeInclude.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/156)

Change name of 'Move' menu to 'Move Field'

---

Src/LexText/Interlinear/FocusBoxController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/160)

Simplify UpdateButtonState methods in FocusBoxController

---

DistFiles/Language Explorer/Configuration/Lexicon/browseDialogColumns.xml
DistFiles/Language Explorer/Configuration/Parts/LexEntryParts.xml
DistFiles/Language Explorer/Configuration/Parts/MorphologyParts.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/176)

Implement LT-21783 - Add new column for Allomorph Stem Names

---

Src/LexText/ParserCore/ParserCore.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/179)

Add file needed for Jenkins to compile FieldWorks

---

Src/LexText/Interlinear/FocusBoxController.ApproveAndMove.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/183)

LT-21896: Force Ctrl + J to skip Free Translation line

---

Src/LexText/ParserCore/HCParser.cs

I fixed LT-21967 (null pointer error).  I also noticed that the code for "DelReapps" was incorrect, and fixed it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/189)

Fix LT-21967

---

Src/xWorks/LcmWordGenerator.cs

Change-Id: I5a2a896fc794a5bd88f6e10d7eda88c5eb298610
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/201)

LT-21968: Word Export Target Office 2019

---

.github/workflows/CI.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/203)

Update setup-dotnet to version 4

---

Build/mkall.targets
Build/nuget-common/packages.config

This fixes https://jira.sil.org/browse/LT-21939 (Hermit Crab reporting a null object reference).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/202)

Update to the latest SIL.Machine library

---

Build/mkall.targets
Build/nuget-common/packages.config
Src/AppForTests.config
Src/Common/Controls/FwControls/FwControls.csproj
Src/Common/FwUtils/FwUtils.csproj
Src/Common/ScriptureUtils/ScriptureUtils.csproj
Src/Directory.Build.targets
Src/FwCoreDlgs/FwCoreDlgs.csproj
Src/FwCoreDlgs/FwCoreDlgsTests/FwCoreDlgsTests.csproj
Src/FwParatextLexiconPlugin/FwParatextLexiconPlugin.csproj
Src/LexText/ParserCore/ParserCore.csproj
Src/Paratext8Plugin/ParaText8PluginTests/Paratext8PluginTests.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/218)

Revert System.ValueTuple hack removal

---

Src/Common/FieldWorks/App.config
Src/LCMBrowser/App.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/219)

Fix the ValueTuple redirect in FieldWorks and add it to LCMBrowser

---

Src/Common/FieldWorks/App.config
Src/Paratext8Plugin/ParaText8PluginTests/App.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/220)

Update icu.net redirects (may fix ParatextIntegration)

---

Lib/Directory.Build.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/221)

Stabilize the build by adding the System.ValueTuple hack to Lib

---

Src/xWorks/CssGenerator.cs

Add a lock to GetBestUniqueNameForNode() to protect against potential additional callers.  Currently the only caller already established a lock.
Change-Id: Id8721fd2982c5e62c4aa8ffb22e4d3d2e2ac2e76
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/223)

LT-21882: Add lock

---

Src/LexText/Interlinear/SandboxBase.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/226)

Fix LT-21998: Crash occurs while performing Morphemes

---

Src/xWorks/XhtmlDocView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/236)

LT-21990: Refresh dictionary on publication change

---

Src/UnicodeCharEditor/App.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/238)

Fix LT-22007: Add binding redirect for icu.net

---

DistFiles/Language Explorer/Configuration/Lexicon/browseDialogColumns.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/240)

Change Lexicon Edit column name to "Stem Name (Allomorph)"

---

Build/Installer.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/243)

Update Base build FlexBridge installer to 4.2.0

---

Src/Common/Controls/XMLViews/ColumnConfigureDialog.cs

I changed ColumnConfigureDialog to use all of the writing systems instead of just the currently selected ones.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/247)

Fix LT-22001

---

Src/xWorks/LcmWordGenerator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/258)

Fix string null check in Word Generator

---

Src/xWorks/ConfiguredLcmGenerator.cs
Src/xWorks/DictionaryPublicationDecorator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/261)

LT-21053: Update homographs to match publication

---

.github/workflows/CI.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/272)

Use wildcard for release branch filters

---

DistFiles/Language Explorer/Configuration/DictionaryConfiguration.xsd
DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Hybrid.fwdictconfig
DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Lexeme.fwdictconfig
DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Root.fwdictconfig
DistFiles/Language Explorer/DefaultConfigurations/ReversalIndex/AllReversalIndexes.fwdictconfig
Src/xWorks/DictionaryConfigurationController.cs
Src/xWorks/DictionaryConfigurationMigrator.cs
Src/xWorks/DictionaryConfigurationModel.cs
Src/xWorks/DictionaryNodeOptions.cs
Src/xWorks/PictureConfiguration.cs
Src/xWorks/xWorks.csproj
Src/xWorks/xWorksTests/DictionaryConfigurationMigrators/DictionaryConfigurationMigratorTests.cs
Src/xWorks/xWorksTests/DictionaryConfigurationModelTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/277)

Add Pictures to DictionaryConfiguration options (LT-22053)

---

Src/FdoUi/InflectionClassEditor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/280)

Refactor DoIt method in InflectionClassEditor.cs

---

DistFiles/Language Explorer/Configuration/DictionaryConfiguration.xsd
Src/xWorks/ConfigurableDictionaryNode.cs
Src/xWorks/CssGenerator.cs
Src/xWorks/DictionaryConfigurationMigrators/FirstAlphaMigrator.cs
Src/xWorks/DictionaryConfigurationMigrators/FirstBetaMigrator.cs
Src/xWorks/DictionaryConfigurationModel.cs
Src/xWorks/DictionaryDetailsController.cs
Src/xWorks/DictionaryDetailsView/PictureOptionsView.Designer.cs
Src/xWorks/DictionaryDetailsView/PictureOptionsView.cs
Src/xWorks/PictureConfiguration.cs
Src/xWorks/xWorksStrings.Designer.cs
Src/xWorks/xWorksStrings.resx
Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs
Src/xWorks/xWorksTests/CssGeneratorTests.cs
Src/xWorks/xWorksTests/DictionaryConfigurationControllerTests.cs
Src/xWorks/xWorksTests/DictionaryConfigurationModelTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/286)

Add css support for document wide image settings

---

Src/xWorks/WordStylesGenerator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/289)

LT-22049: Use default vernacular WS style for Letter Heading

---

Src/xWorks/ConfiguredLcmGenerator.cs
Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/290)

Fix LT-22078: Correct lexical reference targets css classname

---

Src/xWorks/LcmWordGenerator.cs

In order to balance columns in the last page of the Word doc, a 2-column section properties element needs to be added into the paragraph properties of the last paragraph of the doc, in addition to section properties being added as the last child element of the doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/291)

LT-22081: Fix unbalanced columns on last page of exported doc

---

Src/LexText/ParserCore/ParseFiler.cs
Src/LexText/ParserUI/ParserListener.cs

Ron Lockwood reported a few more capitalization problems (https://jira.sil.org/browse/LT-22082).  They were fairly easy to fix.
I think that this belongs in release/9.2 (Sprint 14?).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/295)

LT-22082: Still having capitalization problems

---

Src/LexText/LexTextControls/BaseGoDlg.cs
Src/LexText/LexTextControls/LinkAllomorphDlg.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/304)

LT-21461: Prevent crash on double-clicking abstract entry

---

Src/xWorks/WordStyleCollection.cs
Src/xWorks/WordStylesGenerator.cs

Change-Id: I3594302e51427d55ee4dc05452953ca829358c70
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/312)

Word Export: Change ‘root’ to ‘Normal Font’

---

Src/xWorks/DictionaryConfigurationListener.cs

Jumping to a reversal index entry set the reversal index, but if the reversal index config hadn't been set then it picked the reversal index config based on LangProject.DefaultAnalysisWritingSystem.Id and set the reversal index based on it.  This led to it looking for the English word in the Portuguese reversal index.
I fixed this by changing TryMatchingReversalConfigByWritingSystem to try the writing system of ReversalIndexGuid first, and only try LangProject.DefaultAnalysisWritingSystem.Id if that failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/316)

Fix LT-22104: Fails to navigate to correct Reversal Indices

---

Src/xWorks/LcmWordGenerator.cs
Src/xWorks/WordStyleCollection.cs
Src/xWorks/WordStylesGenerator.cs

Fixes issues with multiple pictures styles being created, and some resulting linking issues between pictures style & picture paragraphs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/317)

Make pictures style global

---

Build/Localize.targets
Build/Src/FwBuildTasks/Localization/ProjectLocalizer.cs
FLExInstaller/CustomFeatures.wxi

* Add the zlm ComponentGroupRef to the Malay feature
* Improve debugging for localization:
Require the LcmRootDir for copyLocales
Improve handling of process exceptions in the multi-threaded process runner
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/318)

Install zlm directories for Malay (second attempt)

---

Src/xWorks/ConfiguredLcmGenerator.cs
Src/xWorks/DictConfigModelExt.cs
Src/xWorks/UploadToWebonaryModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/322)

Fix LT-21879: Escape Copyright/License, normalize filename

---

Src/FwCoreDlgs/FwDeleteProjectDlg.cs

Changed SelectionMode so that you must use Control to make multiple selections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/325)

Fix LT-22072: Don't have Delete Project be multi-select on click

---

Src/Common/Controls/DetailControls/Slice.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/327)

Fix LT-22111: The insertion of 'Allomorph' results in a crash

---

Src/xWorks/WordStyleCollection.cs

If a style with a ws tag was identical to the same style without the ws tag (the default) then in an effort to reduce the number of styles in the Word document we were changing all references to the style with the ws tag to the style name without the ws tag. That optimization was undesirable so we now leave the style with the ws tag.
Change-Id: I7dbdc54c2581bc5cbcc46eaab7be65b7901836f5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/329)

Word Export: LT-22106: Leave ws tag on styles

---

Src/xWorks/LcmWordGenerator.cs

Fix textbox width to match the user-specified max width.
Otherwise, if textbox width matches the actual image width, then when images are narrower than the max width
the textbox containing picture and caption will be narrow, and there will be less space for the caption than in other textboxes.
Example of current behavior with textbox width = image width:
Example of new behavior with textbox width = max width:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/330)

Word Export: Fix caption width

---

Build/mkall.targets
Build/nuget-common/packages.config
Src/AppForTests.config
Src/Common/FieldWorks/App.config

* Contains fixes for LT-22032, LT-21729, LT-9222, LT-21206, LT-21205, LT-21941
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/331)

Update liblcm to 11.0.0-beta0120 for bugfixes

---

Build/Installer.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/333)

Rescue the patching from NHunspell.dll removal

---

Build/Installer.targets
Src/xWorks/DictionaryPublicationDecorator.cs
Src/xWorks/UploadToWebonaryController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/336)

Fix LT-21766 (and also fix patch build)

---

Src/xWorks/LcmWordGenerator.cs

Support an additional case where the content can each be displayed in its own paragraph.
Change-Id: I6a4f75eb529d15c0aa17975f2a6f3c5792944973
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/335)

Word Export: LT-22116: Support content in paragraphs

---

Src/xWorks/FwXWindow.cs

I blindly copied StopSaveTimer from CommitAndDisposeCache, but it isn't appropriate for when the window loses the focus.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/340)

LT-21729: Don't stop timer

---

Src/xWorks/ConfiguredLcmGenerator.cs
Src/xWorks/DictionaryPublicationDecorator.cs
Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/338)

Fix LT-22076: Update generator handling for HeadWordRef fields

---

Build/Localize.targets

* Another attempt at solving LT-21963
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/341)

Copy ms to zlm before zipping up the localized lists

---

Build/mkall.targets
Build/nuget-common/packages.config

LT-22121 is going to take more work to do properly, so we are postponing this until after the stable release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/351)

Undo LT-22121

---

DistFiles/Language Explorer/Configuration/Lexicon/browseDialogColumns.xml

Marlon had some questions about how LT-21907, so we are going to postpone this until after the stable release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/361)

Undo fix for LT-21907

---

Src/LexText/Lexicon/ReversalIndexEntrySlice.cs

This fixes https://jira.sil.org/browse/LT-21441.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/383)

Fix LT-21441: Reversal Entries field existing data hidden

---

Src/GenerateHCConfig/App.config

Modify the config file to use the correct version of SIL.Lexicon
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/400)

Fix for LT-22199

---

Build/mkall.targets
Build/nuget-common/packages.config
DistFiles/Language Explorer/Configuration/Parts/LexSenseParts.xml

This fixes https://jira.sil.org/browse/LT-22133.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/414)

Fix LT-22133: Display Label should apply to Inflection Features

---

Src/LexText/LexTextControls/PopupTreeManager.cs

* I'm not sure why this sometimes worked and sometimes didn't but this solution should eleminate many variables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/418)

Fix LT-22225: Set combo WritingSystemFactory in the manager init

---

Build/mkall.targets
Build/nuget-common/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/430)

Update liblcm to get the bugfix for LT-22197

---

Build/mkall.targets
Build/nuget-common/packages.config

Change-Id: Ic4666f7563c013817b03b69103a4430816573d8c
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/436)

Update liblcm to 11.0.0-beta0131

---

.github/workflows/base-installer-cd.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/468)

Diagnose artifact error

---

DistFiles/Language Explorer/Export Templates/Filtered-LIFT.xml
DistFiles/Language Explorer/Export Templates/LIFT.xml

This corrected an broken URL in the LIFT export notes.
Change-Id: I3cbb54f0a7b4a1dd8ab026938618be5b7d69a449
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/475)

LT-22291 Correct LIFT URL
