sillsdev/FieldWorks

.gitattributes, .github/workflows/CI.yml, Src/views/Test/RenderEngineTestBase.h, Src/views/Test/TestVwGraphics.h
Cherry-pick the 4 commits on develop that introduce the CI builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/13)
=> Add CI to the release branch

Src/xWorks/LcmWordGenerator.cs
This adds the basic table data, without styling. Styling
will be added in a separate change.
Tables cannot be added to a paragraph, they need to be added
directly to a Body. So, the majority of this change was to
not create paragraphs until the end of the process; when we
are in AddEntryData().
What previously was a single paragraph for
the Entry, could now be multiple paragraphs if there are one or
more tables not at the end of the Entry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/14)
=> LT-21672: Add Tables to Word Export

.github/workflows/check-whitespace.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/16)
=> Add CI check for whitespace (calling the git workflow for it)

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs
This adds support for when a style is applied to a specific cell or when different styles are applied to different pieces of the text in a cell.
Note: The changes in SetRunStyle() also add support for styles that are applied to all or a portion of the text in other fields (notes, custom fields …).
Change-Id: Id1ca7ccfaeaad7e7ea7e781263151b1714d9d90f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/17)
=> LT-21672: Add styles to table cells

Src/xWorks/LcmWordGenerator.cs
Add the following table styles:
- Add bold for column headers.
- Add support for column spanning.
- Support left, center, and right cell alignment.
- Center the table title so that it spans all table columns.
Change-Id: I47f40a9ff7713ceba97d00623e5669b2576237db
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/21)
=> LT-21672: Add remaining styles to tables

Build/buildLocalLibraries.sh
Fixes https://jira.sil.org/browse/LT-21764 by allowing hyphens in branch names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/23)
=> Fixes LT-21764.

Src/LexText/Interlinear/FocusBoxController.cs
Fix the position of the unlink button when the writing system is right to left.
Change-Id: I818384b8066213b570c39155137ad18ef842d10a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/24)
=> LT-20855: Fix unlink button position for right to left

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs, Src/xWorks/xWorks.csproj
Create image part for a word doc, create images,
clone images between document fragments,
and track relationship IDs of images.
Export caption text. Formatting of image captions
will be handled separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/22)
=> Add images to word export

Src/Generic/UtilSil.cpp, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
- Reconfigure images to be inline instead of anchored. (Textframes require inline images; textboxes require anchored.)
- Clean up cloning of image runs.
- Create a global paragraph style to use for textframes.
- Link textframe style to images and their captions and ensure image and associated caption are added to the same textframe.
- Ensure Word does not merge adjacent images into the same textframe. This requires adding an empty paragraph between the image textframes, otherwise Word will automatically merge them into a single textframe that can't be split.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/28)
=> LT-21708 Add image and caption textframes to word export

Src/LexText/Interlinear/InterlinDocForAnalysis.cs, Src/LexText/Interlinear/SandboxBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/31)
=> LT-20853: Fix FocusBox word bundle elements' order

Src/xWorks/UploadToWebonaryController.cs, Src/xWorks/xWorksStrings.Designer.cs, Src/xWorks/xWorksStrings.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/33)
=> Fix LT-21713: Clear the error status during cold start retry

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
- Add based on property when generating styles from LCM stylesheet that have based on specified in FLEx.
- Edit styleDictionary to store individual styles instead of groups of styles.
- Revise AddStyles so it adds each style one time only, using the stylenames instead of css classes as the dictionary keys.
NOTE: In the Word export, the style dictionary should save each style individually rather than a collection of styles associated with a given css class.
Otherwise, any given style may be added to the styles xml multiple times, once for each css class using that style.
Remaining task:
- Homograph-Number style is still being duplicated. It is handled in a different function and requires its own fix.
Change-Id: I9530c894fdae8251ab4211f1c7529fa63586b446
- - -
This change is [<img …
=> Add BasedOn style property and fix duplicate styles

Build/nuget-common/packages.config, Src/LexText/Interlinear/ITextDllTests/ITextDllTests.csproj
You need to add NUnit3TestAdapter to each csproj file that you want to run from within VisualStudio:
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">
<Import Project="..\..\..\..\packages\NUnit3TestAdapter.4.3.2\build\net35\NUnit3TestAdapter.props" />
<PropertyGroup>
...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/34)
=> Fix NUnit by adding NUnit3TestAdapter

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/WordStylesGenerator.cs
Change-Id: I7f9835e66c6aaa5cb9039cc586683c1cb0311138
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/35)
=> LT-21761: Add Table indenting and right justification

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
Change-Id: I3c558a1a9337dfa2bf11ae21133fb49df2461f14
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/39)
=> LT-21674: Use Dictionary-Context style for Before/After

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
The first line of an entry typically uses FirstLineIndent to indented to the left. When we have multiple paragraphs for an entry (because the entry contains Tables or Pictures) then we do not want the line following the Table or Picture to also be indented to the left. We now create a ‘continuation’ style for paragraphs following a table or picture.  It is the same as the original style except it does not use FirstLineIndent.
Change-Id: I67e282e4a02f1ff9145dfb198c4432823d156413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/37)
=> LT-21761: Fix indenting for the first line after a Table

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
- When starting a run, add a writing system style if the run has a WS specified.
- If the run should have an additional style associated with it, replace the writing system style with a link to the writing system specific version of the additional style.
- Use RunFonts object instead of Font object to specify fonts for character styles in word.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/38)
=> LT-21751: Implement writing system styles

Src/xWorks/DictionaryExportService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/41)
=> Fix reversal export naming & don't export empty reversals

Src/xWorks/LcmWordGenerator.cs
Fixed the problem with the continuation style being written to paragraphs containing images/captions (instead of the textframe style being written).
To prevent the problem with the paragraph following the image/caption from using the textframe style, we now base the continuation style on the first paragraph instead of the last.
Change-Id: Ibae531ebf142719d55b912efe72746299a1ce642
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/44)
=> LT-21778: Fix image textframe styles

Src/xWorks/LcmWordGenerator.cs
There are no logic changes in this PR, just cleanup.
- Changed the name of some methods.
- Changed eachInAParagraph to eachOnANewLine. For Word Export a Paragraph is a class and carries a specific meaning. We are not putting the data in a separate OpenXml.Wordprocessing.Paragraph, just starting a new line. So I changed the names to try and reduce confusion.
Change-Id: I94eca41b7fa173b04990877429ab607736aa7774
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/49)
=> Word Export: Code cleanup

Src/LexText/Interlinear/InterlinMaster.cs, Src/xWorks/LcmWordGenerator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/52)
=> Do some minor refactoring in InterlinMaster.cs

Src/Transforms/Presentation/FormatHCTrace.xsl
I made the change requested by Andy Black.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/64)
=> LT-21798: Improve partialParse message in Hermit Crab trace

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs
Converting the fragment to a string was resulting in the
loss of all styling for Word Export.  Now we pass the
content fragment to both AddLexReferences() and AddCollection().
The xhtml and json generators do the conversion to a string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/62)
=> Pass a fragment to AddLexReferences and AddCollection

Src/LexText/Interlinear/ChooseAnalysisHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/72)
=> LT-21786: Show variant info for analysis chooser

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/WordStylesGenerator.cs
- When a run is created set the style name. (It may get modified with basedOn information as we get other notifications.)
- Add styles during run creation.
- Allow styles to be based on other styles, which can be based on other styles…
- Support different styles on different document fragments.
TODO:
A remaining task is to change the style names from the config.Style to the config.DisplayLabel.  This will improve the style names that appear in Word. At that time we will need to add additional code to generate a unique style name if the properties of a style are different.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/77)
=> LT-21785: Add more style support

Build/mkall.targets, Build/nuget-common/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/79)
=> LT-21760: Update LCM version

Src/LexText/LexTextDll/LexTextApp.cs
I changed name of conceptual intro file.  This assumes that the latest version of FwHelps is in DistFiles\Helps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/81)
=> LT-21763: Update to latest version of the Intro to parsing document

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
This submission adds support for displaying the style Display Name in the Word Styles dialog (instead of displaying the style Id).
This addresses the main cases; more work is needed to handle the ‘normal’ styles, “Dictionary-Normal”, abbreviations, paragraph Styles properties, and the possibility of the same Display Name being used by different style Ids.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/84)
=> Word Export Style Display Names

Src/LexText/Interlinear/InterlinVc.cs
Show infl variant info for unapproved words in Word Analyses
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/89)
=> LT-21787: Show infl variant info in Word Analyses

Src/LexText/Interlinear/InterlinDocRootSiteBase.cs, Src/LexText/Interlinear/InterlinVc.cs
A change in how GetBestGuess works on May 1st provoked this problem.  I fixed it by changing how the display gets notified that wordforms may have been updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/90)
=> Fix LT-21814: Guess Word not working properly for the repetitive words in the Analyze tab

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
When building a style that is based on another style, make sure we are not creating a new style with a root that is the same as the root of the basedOn style.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/88)
=> Word Export: Fix multiple root names that are the same

Src/LexText/ParserCore/ParserWorker.cs
WfiWordformServices.FindOrCreateWordform needs to be done within a unit of work, but you get a props change error if you wrap it with UndoableUnitOfWorkHelper.DoUsingNewOrCurrentUOW.  So I used TryGetObject instead.  If it doesn't exist, then nothing needs to be updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/86)
=> Fix LT-21810: Yellow Crash occurs while parsing with Default Parser(XAmple)

Src/xWorks/LinkListener.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/94)
=> LT-21787: Fix hyperlink to another project

Src/LexText/Interlinear/SandboxBase.cs
The background of a word should only be made yellow if there are multiple analyses AND the user hasn't chosen an analysis yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/95)
=> Fix LT-21815: Yellow backgrounds not working properly

Src/xWorks/LinkListener.cs
Fix FollowActiveLink method with intra-project links
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/99)
=> LT-21821: Fix certain links to other area of project

Src/LexText/Interlinear/InterlinDocForAnalysis.cs, Src/LexText/Interlinear/InterlinDocRootSiteBase.cs, Src/LexText/Interlinear/InterlinTaggingChild.cs, Src/LexText/Interlinear/InterlinVc.cs, Src/LexText/Interlinear/InterlinViewDataCache.cs, Src/LexText/Interlinear/SandboxBase.cs
I changed FieldWorks so that it could guess occurrences based on the previous word.  I also made InterlinViewDataCache be a guess cache instead of a decorator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/97)
=> Lt 21728c: Parse Prioritizer

DistFiles/Language Explorer/Configuration/Words/areaConfiguration.xml, Src/LexText/ParserCore/ParserReport.cs, Src/LexText/ParserUI/ParserListener.cs, Src/LexText/ParserUI/ParserReportDialog.xaml, Src/LexText/ParserUI/ParserReportDialog.xaml.cs, Src/LexText/ParserUI/ParserReportViewModel.cs, Src/LexText/ParserUI/ParserReportsDialog.xaml, Src/LexText/ParserUI/ParserReportsDialog.xaml.cs, Src/LexText/ParserUI/ParserReportsViewModel.cs
I made the following improvements:
- Make Parser Reports window be a singleton
- Make On Testbed work
- Add button to show word analyses
- Make diff always subtract the older report from the newer report
- Rename menu:
Run Tests
On Testbed
On Current Text
On All Texts
Show Test Reports...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/105)
=> Lt 21835: Improve Parser Testbed UI

Src/xWorks/XhtmlDocView.cs
This fixes a bug that I introduced on 7/10 when trying to fix the second test of LT-21702.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/108)
=> LT-21838: Force a refresh

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
- Abbreviations should have a hard-coded space added after (similar to GenerateCssForWritingSystemPrefix() in CssGenerator.cs).
- Added Between text to senses.
- Fixed the positioning of the Before and After text when applied to multiple senses with gram info.
- When adding a writing system prefix it needs to be added after the before/between content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/114)
=> Word Export: Fix Before/Between/After issues

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
Properties, like ‘DateModified’, were not displaying before/after text and were not using the correct style.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/119)
=> Word Export: Support Before/After and Style for properties

Src/LexText/ParserUI/ParserListener.cs, Src/LexText/ParserUI/ParserReportsDialog.xaml.cs, Src/LexText/ParserUI/ParserReportsViewModel.cs
I fixed the problem where deleting reports didn't cause the Compare button to be greyed out.
I also fixed a problem where reports that were added to the parser reports window weren't notifying the buttons when they were selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/126)
=> Fix LT-21854: Delete reports button not working properly

Src/LexText/ParserUI/ParserReportsDialog.xaml, Src/LexText/ParserUI/ParserReportsDialog.xaml.cs
I fixed this by adding code to catch PreviewMouseWheel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/128)
=> Fix 21855: Scrolling function in Parse Test Reports

Src/xWorks/LcmWordGenerator.cs
We need to use the config.DisplayLabel instead of the config.Style for the style reference.  Some cases were previously working because these values were the same.
The change to the AddStyle() call was to fix a problem with the way paragraph styles were organized in the collection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/129)
=> Word Export: Fix indenting problem

Src/LexText/ParserUI/ParserReportsDialog.xaml, Src/LexText/ParserUI/ParserReportsDialog.xaml.cs
I turned off selection in favor of the Select check box.  I also fixed a crash that occurred if you double clicked with the right mouse button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/130)
=> Fix LT-21858: Parser test reports pane highlights inaccurate report

Src/xWorks/WordStylesGenerator.cs
The horizontal anchor type for the textframe should be set to text rather than margin.
A text type anchor prompts the textframe to move with the text it is anchored to, while a page or margin type anchor would keep the textframe fixed in a particular location on the page.
If the horizontal anchor type is set to page or margin, images can appear in the wrong column when the document layout is set to two columns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/133)
=> Fix 2-column display by correcting image anchor

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs, Src/xWorks/WordStylesGenerator.cs
Fix missing styles.
Fix incorrect basedOn style names.
Continuation styles are now based on other continuation styles. Add code to set the RTL flag. (use will be in a separate submission.) For the ‘Normal’ style set the default font name and font size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/138)
=> Word Export: Fix paragraph style problems

Build/mkall.targets, Build/nuget-common/packages.config, Src/xWorks/FwXWindow.cs
This was fixed by changing PhonologyServices in liblcm and also doing a Master Refresh.  I removed ProgressDialogWithTask because it crashed trying to unlock something that had already been unlocked.  The Master Refresh indicates when the import is done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/142)
=> Fix LT-21872: Import Phonology crashes in Grammar area

Src/LexText/ParserCore/ParserCoreTests/ParseWorkerTests.cs, Src/LexText/ParserCore/ParserWorker.cs
The grammar couldn't parse "Frau", but this wasn't obvious to the user because TryAWord tried both uppercase and lowercase and only reported the lowercase error.  I changed TryAWord to assume that the user used the case that they wanted.  This allows the user to see the uppercase error.   If the user wants to see the lowercase results, then they can try the lowercase version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/143)
=> Fix LT-21862: Parser can't find German nouns (caps)

Src/xWorks/ConfiguredLcmGenerator.cs
The wrong node was being passed to AddLexReferences().
Note: This change does not impact LcmXhtmlGenerator. It’s implementation does not use the node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/148)
=> Word Export: Fix duplicate & missing before and after

Src/LexText/ParserCore/ParserReport.cs, Src/LexText/ParserUI/ParserListener.cs, Src/LexText/ParserUI/ParserReportsDialog.xaml, Src/LexText/ParserUI/ParserReportsDialog.xaml.cs, Src/LexText/ParserUI/ParserReportsViewModel.cs, Src/LexText/ParserUI/ParserUIStrings.Designer.cs, Src/LexText/ParserUI/ParserUIStrings.resx
I added a comment field to Parser Test Reports.  I also added a Save Report button.  If reports aren't saved, they are lost when the user closes the project.  When the user saves a report, they get a popup menu asking for a comment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/149)
=> Fix LT-21863: Add comment field to Parser Test Reports

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs
- Add between content for CrossRreference types.
- Add before and after content for LexicalRelations->Targets.
Note: I think passing child to AddCollection() is the correct node for the collection being added. The other implementations of AddCollection() do not use this parameter so they are not affected.
This fixes one of the issues identified in LT-21808.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/155)
=> Word Export: Add missing Before/After/Between content

Src/xWorks/LcmWordGenerator.cs
Removed TODO’s for content we do not plan to support for Word Export.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/158)
=> Word Export: Remove TODO’s for Audio and Video content

Src/xWorks/LcmWordGenerator.cs
When senses are in separate paragraphs we were still adding the before and after content that was around the collection of senses.  It is now only added when not in separate paragraphs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/159)
=> Word Export: Prevent extra Before/After content for senses

Src/GenerateHCConfig/ConsoleLogger.cs, Src/LexText/ParserCore/HCLoader.cs, Src/LexText/ParserCore/HCParser.cs, Src/LexText/ParserCore/IHCLoadErrorLogger.cs, Src/LexText/ParserCore/ParserCoreStrings.Designer.cs, Src/LexText/ParserCore/ParserCoreStrings.resx, Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs, Src/Transforms/Presentation/FormatCommon.xsl
I fixed LT-21585 by detecting and reporting errors in rewrite rules when they are loaded into HermitCrab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/161)
=> Fix LT-21585: Hermit Crab Parsing Error yellow box crash

Src/LexText/Morphology/AffixRuleFormulaControl.cs
I added a check to avoid reading outside of an array.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/162)
=> Fix LT-21890: Deleting from right side of affix process rule crashes

Src/LexText/Morphology/AffixRuleFormulaControl.cs
I unscheduled the removal of a column that was being removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/163)
=> Fix LT-21886: Deleting phonemes from an affix rule crashes

Src/LexText/ParserCore/HCLoader.cs
I have a fix for this bug, but Andy wants me to do something more ambitious.  Here is the background:
When NotOnClitics is disabled, FieldWorks asks HermitCrab to apply the rules in the following order (in generation direction):
morphological rules -> phonological rules -> clitic rules
When NotOnClitics is enabled, FieldWorks asks HermitCrab to apply the rules as follows:
morphological rules -> phonological rules -> clitic rules -> phonological rules
This causes the phonological rules to be applied twice to the non-clitic portion, which is not what the grammar writer intended.
I fixed this by having FieldWorks ask HermitCrab to apply the rules as follows:
morphological rules -> clitic rules -> phonological rules
This produces the desired result: the phonological rules apply to the clitics …
=> Fix LT-21892: NotOnClitics box does not work as expected

Src/LexText/Morphology/AffixRuleFormulaControl.cs, Src/LexText/Morphology/RuleFormulaControl.cs
I fixed https://jira.sil.org/browse/LT-20588.  The problem was that doing an undo left the context-sensitive menu in a funny state.  I couldn't figure out how to trigger a reset of the menu when the undo was performed, so I settled for triggering a reset if the user clicked on any of the elements in the the menu. In general, if the user clicks anywhere then the menu will reset, so this change is just to make sure that clicking on a menu item won't cause a crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/167)
=> Fix LT-20588: Crash in Affix Process Rule

Src/LexText/ParserCore/HCLoader.cs, Src/xWorks/CssGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs, Src/xWorks/WordStylesGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
A remaining task is to support font properties on the bullet or number characters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/168)
=> Word Export LT-21768: Add Bullets and Numbering

Src/xWorks/LcmWordGenerator.cs
Fixed the problem with some pictures causing the export to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/169)
=> Word Export LT-21942: Fix export failure

Src/LexText/LexTextControls/PatternView.cs
I have a fix for this, but it might not be the best solution.
If you select a boundary marker (or any phoneme) in a phonological rule and type a character, its name gets deleted but the boundary marker does not.  I couldn't track down where in the code this happens.  I prevented this from happening by suppressing all characters except for Backspace and Delete.  This means that the user can only enter phonemes by using the menu provided.  This feels like overkill, but Matthew is OK with it if we eventually add code to allow phonemes to be entered by typing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/165)
=> Fix LT-21888: boundary marker name can be deleted when editing rules

Src/xWorks/LcmWordGenerator.cs
When testing with Steve’s Project additional failures were found:
1. Open image files with read access. The same image can be used by multiple entries. We were trying to open the same file with write access from different threads.
2. Use FirstOrDefault() instead of First().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/171)
=> Word Export LT-21942: Fixed more Export failures

Src/Common/Controls/Widgets/FwComboBox.cs, Src/Common/Controls/Widgets/PopupTree.cs, Src/LexText/LexTextControls/MSAGroupBox.cs
Fix behavior of grammatical info dropdown in the New Entry dialogue.
- Correct the variable used to overwrite width in ShowDropDownBox() in the case that width is explicitly specified for the listbox.
- Specify DropDownWidth for the MainPOS dropdown to match the default width for popuptree.
- The AffixTypes dropdown is meant to match button width, so its DropDownWidth should not be explicitly set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/173)
=> Fix gram info dropdown: LT-21584 Part2

Src/views/VwSelection.cpp
Analyzing the data that caused the crash showed that in some edge
cases no writing system can be identified in MakeSubString.
This could cause an empty builder to have no writing system.
I couldn't identify any actual side effects in this edge case so
I left the assert, but allowed the paste to succeed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/174)
=> Fix LT-21839: Avoid crash and allow paste success with no ws

Src/xWorks/LcmWordGenerator.cs
Runs containing drawings (pictures) need to be in their own Paragraph. When we are in SeparateIntoFirstLevelElements() don’t combine them with other elements in a paragraph.  Instead leave the run as a first level element so that later, in AddEntryData(), it will get put in its own paragraph with the correct style.
Change-Id: Ie62eb2edb7547d553018a61ea57b638dc146d407
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/177)
=> Word Export LT-21942: Fix picture clipping problem

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs
Add font property support for bullets and numbers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/178)
=> Word Export LT-21768: Font properties for bullets

Src/Common/Controls/DetailControls/DataTree.cs, Src/Common/Controls/DetailControls/DetailControlsTests/SliceTests.cs, Src/Common/Controls/DetailControls/Slice.cs, Src/Common/Controls/DetailControls/SliceFactory.cs, Src/LexText/Lexicon/LexReferenceMultiSlice.cs, Src/LexText/Lexicon/RoledParticipantsSlice.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/182)
=> Remove slice cache that never had a hit and was of limited use

Src/LexText/Morphology/AffixRuleFormulaControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/185)
=> Fix LT-21956: Crash when doing Ctr+A in 'Affix Process Rule' result area

Src/LexText/Interlinear/FocusBoxController.cs, Src/LexText/Interlinear/InterlinDocForAnalysis.cs
LT-21965 was introduced in July when I changed the guesser to guess based on occurrence of an analysis rather than just the analysis itself.  An occurrence is just the segment and its index.  Linking two words together changes the indices, hence the problem.  I fixed the bug by resetting the analysis cache after linking words or breaking phrases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/191)
=> Fix LT-21965: Linking words in interlinear is broken

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs, Src/xWorks/WordStylesGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
- Use the default vernacular writing system for before/after/between content.  This causes the order of many runs to be correct and causes characters like parentheses to be display correctly.
- For situations where two runs that are both lt2 we now add a run between them that is rtl.  This causes the order to be switched so they appear the same as in FLEX.
- Sense numbers now generate before/after content the same as all other before/after content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/192)
=> Word Export LT-21673: Add support for bidi text

Src/xWorks/UploadToWebonaryController.cs, Src/xWorks/UploadToWebonaryDlg.Designer.cs, Src/xWorks/UploadToWebonaryDlg.cs, Src/xWorks/UploadToWebonaryDlg.resx, Src/xWorks/UploadToWebonaryModel.cs, Src/xWorks/WebonaryLogViewer.Designer.cs, Src/xWorks/WebonaryLogViewer.cs, Src/xWorks/WebonaryLogViewer.resx, Src/xWorks/WebonaryUploadLog.cs, Src/xWorks/xWorks.csproj, Src/xWorks/xWorksStrings.Designer.cs, Src/xWorks/xWorksStrings.resx, Src/xWorks/xWorksTests/UploadToWebonaryControllerTests.cs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/187)
=> LT-21706: Modify webonary status reporting

Src/xWorks/WordStylesGenerator.cs
For some writing systems Word was not using the correct font or correct font size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/193)
=> Word Export LT-21673: Fix font problems for bidi text

Src/xWorks/LcmWordGenerator.cs
To be consistent with how FLEX displays consecutive left-to-right runs, we do not want to switch their order. Remove the code that was doing the switching and causing the display to be different between Word and FLEX.
Change-Id: I396a54c88e9952112e396f0157f6420723282dff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/194)
=> Word Export LT-21673: bidi problem with switching run order

Src/LexText/Lexicon/MsaInflectionFeatureListDlgLauncherSlice.cs
The crash occurred in RemoveFeatureStructureFromMSA because it tried to create a new non-undoable unit of work inside a PropChanges broadcast.  The property change was caused when DefaultCreateNewUIObject  created a new object inside an undoable unit of work.  DataTree.PropChanged called DataTree.RefreshList, which removed the existing slices which removed an existing feature structure.
I noticed that there was nothing to be done in the non-undoble unit of work because m_obj's ClassID didn't match.  So, I changed the code to avoid creating the non-undoable unit of work in this case.  This allowed the feature structure to be created without crashing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix LT-21971: Crash adding a Feature Set

Src/Common/Controls/DetailControls/Slice.cs
One small bug in the Move Down code explained all of the weird behaviors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/196)
=> Fix LT-21915: Additional glitches in Move up/Move down options

Src/xWorks/LcmWordGenerator.cs
Prevent Word Export from crashing when we encounter a string that uses a writing system that is not part of the current FLEX project. This can happen when using copy/paste from one FLEX project to another, and the projects use different writing systems. See LT-21981.
Pasting table data from a custom field in one project to a custom field in another project reproduced the crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/197)
=> Word Export: writing system that is not part of the project

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs, Src/xWorks/WordStylesGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
Instead of all BefAftBet content using the same style we now use a style that we get from the content and node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/204)
=> Word Export: support Before/After/Between unique styles

Src/xWorks/ConfigurableDictionaryNode.cs, Src/xWorks/DictionaryConfigurationController.cs, Src/xWorks/DictionaryConfigurationDlg.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/XhtmlDocView.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs, Src/xWorks/xWorksTests/DictionaryConfigurationControllerTests.cs, Src/xWorks/xWorksTests/LcmJsonGeneratorTests.cs
* Generate xhtml with a nodeId attribute that uses the ConfigurableDictionaryNode hash and use that to set highlight
* Modify the 'Configure Dictionary' right click menu to use the nodeId attribute to select the correct tree node
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/199)
=> Fix LT-21737: Make highlight button work

Src/LexText/ParserCore/ParseFiler.cs, Src/LexText/ParserCore/ParserCoreStrings.Designer.cs, Src/LexText/ParserCore/ParserCoreStrings.resx, Src/LexText/ParserCore/ParserWorker.cs, Src/XCore/xWindow.cs
This also improves the user notifications produced when running Run Tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/205)
=> Fixes LT-21934: FLEx freezes when clicking "Close" if parser is running

DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Hybrid.fwdictconfig, DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Lexeme.fwdictconfig, DistFiles/Language Explorer/DefaultConfigurations/Dictionary/Root.fwdictconfig
Change-Id: I86a23c955d0198e007a3ed0479d54a051c97db22
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/206)
=> LT-21982: Make default between/after empty for picture nodes

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/DictionaryPublicationDecorator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/207)
=> LT-21829: Properly remove excluded lex refs

Src/LexText/ParserUI/ParserUIStrings.Designer.cs, Src/LexText/ParserUI/ParserUIStrings.resx, Src/LexText/ParserUI/TryAWordDlg.cs, Src/XCore/xWindow.cs
FLEx freezes because it is waiting for the parser to finish parsing.  It aborts after one minute, but the user doesn't know that.  I added code to change the Try a Word window to say "Stopping parser (this may take up to a minute)".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/208)
=> Lt 21934b: FLEx freezes when closing Try a Word if it is parsing

DistFiles/Language Explorer/Configuration/Parts/LexSenseParts.xml
ChooserNameTS works incorrectly for feature structures, so I switched to LongNameTSS.  ChooserNameTS should be fixed in liblcm at some point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/213)
=> Fix LT-21966: Inflection features not showing correctly in browse

Src/xWorks/LcmWordGenerator.cs
I generalized the code for dealing with "\A" to deal with "\0A", "\a", and "\0a".  I don't know how to test this.  Someone may need to create an acceptance test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/216)
=> Fix LT-21918: Newline symbol \0A printed in output

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
Add guidewords and page numbers to the header that is displayed on every page.
Use a different header layout for even and odd pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/217)
=> Word Export LT-21891: Add guidewords and page numbers

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStylesGenerator.cs, Src/xWorks/xWorksTests/LcmWordGeneratorTests.cs
Change-Id: I737e73956a413561a338738050f847316f6e3089
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/225)
=> Word Export: LT-21891: Add guidewords for reversals

Src/LexText/ParserUI/ParserListener.cs, Src/LexText/ParserUI/ParserReportDialog.xaml, Src/LexText/ParserUI/ParserReportDialog.xaml.cs, Src/LexText/ParserUI/ParserReportViewModel.cs, Src/LexText/ParserUI/ParserReportsDialog.xaml, Src/LexText/ParserUI/ParserReportsDialog.xaml.cs, Src/LexText/ParserUI/ParserReportsViewModel.cs, Src/LexText/ParserUI/ParserUIStrings.Designer.cs, Src/LexText/ParserUI/ParserUIStrings.resx
This implements https://jira.sil.org/browse/LT-21999 with Jason's permission.
It adds a "Save Report" button to the window for individual parser reports.
It adds the comment as a label right after Save Report button.
It changes saving so that you can change a comment by saving the report again (deleting the old report).
It also fixes a bug that prevented comment fields from being updated properly when comments are changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/224)
=> Fix LT-21999: Improve saving of parser test reports

Src/xWorks/WordStylesGenerator.cs
- In Word 2019, a vertical offset must be specified in order for image textframes to display beneath their associated entries.
- We also lock the textframes' anchors for better behavior when users drag a textframe to a new location in Word.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/227)
=> LT-21997: Fix location of pictures in Word export

Src/LexText/ParserUI/ParserReportsDialog.xaml
Beth requested that the width of the parser test reports window be limited so that it would fit on a laptop screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/228)
=> Improve LT-21999: Improve saving of parser test reports

DistFiles/Language Explorer/Configuration/CommonDataTreeInclude.xml
Beth noticed that some menus say "Move" and some say "Move Field".  This is because multistrings have a separate menu that includes a menu item for changing the writing system.  This did not get changed when Jason changed the name of the "Move" menu item for the menu for generic objects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/229)
=> Fix LT-22000: "Move" vs. "Move Field"

Src/LexText/ParserCore/ParserReport.cs, Src/LexText/ParserUI/ParserReportDialog.xaml, Src/LexText/ParserUI/ParserReportViewModel.cs
Daney reported some problems with saving comparison reports.  I fixed the problems by disabling the Save Report button on comparison reports.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/232)
=> Fix LT-21999: Disable Save Report on comparison reports

DistFiles/Language Explorer/Configuration/CommonDataTreeInclude.xml, Src/Common/SimpleRootSite/SimpleRootSite.cs, Src/LexText/Interlinear/RawTextPane.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/230)
=> LT-20849: Refresh Baseline on Text switch if VScroll changes

Src/xWorks/WordStylesGenerator.cs
Word does not expect the indentation direction (left/right) to be flipped for right to left output.  Removed the extra code and output the same indentation direction for both LTR and RTL.
This problem also existed with the single column output, but became more obvious when we switched to double column output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/233)
=> Word Export: LT-22006: RTL - Fix indentation and clipping

Src/xWorks/LcmWordGenerator.cs
For right to left documents this sets every section so that the column on the right is filled first.
With this change the user no longer needs to do the following steps in the Word document:
In the Layout tab, click the icon at the lower right of the
Page Setup section, and in the dialog that comes up, set
Section direction: to Right-to-left. This is critical for RTL
documents so that the first column on the page is on the right
side.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/234)
=> Word Export: RTL – Set first column to be on the right

.gitignore, Src/Common/Controls/DetailControls/MSAReferenceComboBoxSlice.cs, Src/LexText/LexTextControls/MSAPopupTreeManager.cs
I created BeforeChange and AfterChange events to delay the refresh of the data tree.  BeforeChange sets DoNotRefresh and AfterChange adds RefreshDataTree to the UI thread's queue.  I tried using BeforeSelect and AfterSelect, but there are actually two calls to AfterSelect and it wasn't clear that I could catch only the second call.  Also, it would force a refresh of the data tree even if nothing was changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/235)
=> Fix LT-21980: Crash changing or modifying grammatical info

Src/LexText/LexTextControls/LinkMSADlg.resx
I widened a box so that the RTL text would show.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/241)
=> Fix LT-20850: RTL hides text

Src/LexText/Interlinear/BIRDInterlinearImporter.cs, Src/LexText/Interlinear/ITextDllTests/BIRDFormatImportTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/242)
=> Fix LT-22008: Do not crash importing flextext with empty word content

Src/Common/Controls/DetailControls/DataTree.cs, Src/Common/Controls/DetailControls/MSAReferenceComboBoxSlice.cs, Src/LexText/LexTextControls/MSAPopupTreeManager.cs
This was another issue where a display object got disposed prematurely.  I came up with a more general solution to the problem by changing DataTree.PropChanged to use BeginInvoke to postpone the change until the invoker is done.  I also removed the fix to https://jira.sil.org/browse/LT-21980 since it is covered by the general solution.  The general solution should work, but I wonder if it is too general.  Jason, could this cause a problem?  Also, should we make this even more general by postponing all of DataTree.PropChanged?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/239)
=> Fix LT-22011: Adding slots lead to crash

Build/Installer.targets, Build/Localize.targets, Build/Src/FwBuildTasks/FwBuildTasks.csproj, Build/Src/FwBuildTasks/FwBuildTasksTests/NormalizeLocalesTests.cs, Build/Src/FwBuildTasks/Localization/CopyLocale.cs, Build/Src/FwBuildTasks/Localization/NormalizeLocales.cs, FLExInstaller/CustomComponents.wxi
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/237)
=> LT-21963: Copy Malay to an alternate writing system code (ms -> zlm)

Src/Common/Controls/DetailControls/DataTree.cs, Src/Common/Controls/DetailControls/GhostStringSlice.cs
This was caused by the fix to https://jira.sil.org/browse/LT-22011.  Basically, most of the time you want to postpone executing DataTree.PropChanged, but sometimes you don't.  Jason should review this to make sure I'm not doing something bad.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/244)
=> Fix LT-22018: Typing lost in example and translation fields

Src/LexText/LexTextControls/LiftMerger.cs
Replaces #248
Reverts 3 unwanted changes from https://github.com/sillsdev/FieldWorks/commit/768611a9ba957b9c364907beea009cbaab23b0ae#diff-f6a37d69740bb35c88809abf63aca915df7dfba5ee3030dc10ca39d990c59571
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/253)
=> Preserve sense examples, subsenses importing from The Combine

DistFiles/Language Explorer/Configuration/ContextHelp.xml, DistFiles/Language Explorer/Configuration/Main.xml, Src/LexText/LexTextDll/LexTextApp.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/252)
=> LT-22021: Add Word export doc to Help > Resources menu

Src/xWorks/RecordClerk.cs
I fixed LT-21962 by using OnChangeFilter instead of setting the Filter property directly.  This allows the column headers to be updated properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/254)
=> Fix LT-21962

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/WordStylesGenerator.cs
Root problem is that some image caption component styles were not based on writing system styles in the Word export.
* Create function "GenerateContentForSimpleString" that gets a writing system and passes it to AddProperty to generate the string property content.
* Use first analysis language as the default writing system for string properties.
* In AddProperty, use AddRun with the writing system to get/create a style that is based on the writing system.
* Delete unused WriteElementContents method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/255)
=> LT-22025: Fix font issues in image captions

Src/xWorks/WordStylesGenerator.cs
Diacritics are cutoff because Word uses exact line spacing when
FLEx specifies at least line spacing.
Fix logic for determining at least and exact line spacing
in the Word Export.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/259)
=> LT-21818: Fix cutoff diacritics in Word Export

Src/xWorks/CssGenerator.cs, Src/xWorks/DictionaryConfigurationDlg.cs, Src/xWorks/xWorksTests/ConfiguredLcmUsfmGeneratorTests.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorReversalTests.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs, Src/xWorks/xWorksTests/CssGeneratorTests.cs, Src/xWorks/xWorksTests/LcmJsonGeneratorTests.cs
- Keep the node path back to the root in the css file.  This is needed to ensure that styles are applied from the most specific (leaf node) to the lease specific (root node).
- All node names now have a unique identifier.  This is to prevent the wrong style from being used when nodes have the same display name (ie. Headword) but are located at different places in the tree. Without the unique identifier a node without a style could end up using a style from a different node with the same display name. With unique names, a node without a style will look to its parent node for style information, and then it’s grandparent node, … up to the root.
- The change in RemoveBeforeAndAfterForNoteInParaRules(): Changed the method so that we keep non-before/after rules. This fixes a problem with notes …
=> LT-22042: Fix incorrect styles being used in Flex

Src/ManagedLgIcuCollator/LgIcuCollator.cs
I replaced null with "" to avoid the crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/268)
=> Fix LT-21953: Sort Reversal Subentries crash when subentry missing form

DistFiles/Language Explorer/Configuration/Lexicon/browseDialogColumns.xml, DistFiles/Language Explorer/Configuration/Parts/LexEntryParts.xml, DistFiles/Language Explorer/Configuration/Parts/MorphologyParts.xml
I added a column for Required Features for Lexemes to the browse view of the Lexicon Entries window.  I also had to change how required features are displayed since the existing code displayed "f" instead of "[nagr: [gen:f]]".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/267)
=> Fix LT-21958 (Required Features for Lexeme Form should be visible)

Src/xWorks/CssGenerator.cs
The style information used for the nodes under
MainEntry->Subentries, is also used for
MainEntry->Senses->Subentries.
Fix the problem so that we now use the style information for both node paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/265)
=> LT-22042: Fix incorrect styles being used for subentries

Src/LexText/ParserCore/ParserWorker.cs
The original code broke because FindOrCreateWordform was not in the scope of a unit of work helper.  Not knowing better, I fixed in LT-21810 by avoided calling FindOrCreateWordform.  But this causes problems if the corpus has an uppercase version of a lowercase word that doesn't appear in the corpus.  So I added a unit of work helper around FindOrCreateWordform that solves both LT-22047 and LT-21810.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/269)
=> Fix LT-22047 without breaking LT-21810

Src/xWorks/RecordClerk.cs
I fixed this by returning if the object no longer exists.  This is a good candidate for release/9.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/276)
=> LT-22063: Crash while navigating to Word Analyses view

Src/LexText/Interlinear/FocusBoxController.ApproveAndMove.cs
In https://jira.sil.org/browse/LT-22047, Ron Lockwood complained that uppercase wordforms that were assigned a lowercase analysis still appeared in the Word Analyses window.  I thought that I had a fix for this issue, but https://jira.sil.org/browse/LT-22064 showed that the uppercase wordform still appeared in the Word Analyses window if you closed and reopened the project before it was assigned a lowercase analysis.  I fixed LT-22064 by explicitly deleting the uppercase wordform if it didn't appear in the corpus when it was assigned a lowercase analysis.
This should be included in release/9.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/279)
=> LT-22064: Issue with uppercase words in "Word Analyses" view

Src/xWorks/DictionaryDetailsController.cs, Src/xWorks/DictionaryDetailsView/PictureOptionsView.Designer.cs, Src/xWorks/DictionaryDetailsView/PictureOptionsView.cs, Src/xWorks/DictionaryDetailsView/PictureOptionsView.resx, Src/xWorks/PictureConfiguration.cs, Src/xWorks/xWorks.csproj, Src/xWorks/xWorksStrings.Designer.cs, Src/xWorks/xWorksStrings.resx
* Add a new DictionaryDetailsView for pictures that modifies the Pictures part of the DictionaryConfigurationModel
- I chose to use the existing picture node to add the interaction as that is most discoverable. I decided that with a lable that indicated that the setting was for *all* pictures in the document a separate dialog was not required. This could prove to be unfounded optimism
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/281)
=> Implement LT-22054: Add UI for setting picture options

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/DictionaryExportService.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs
A nodeId attribute was recently added to the XHTML representation to aid the right-click Dictionary Configuration option in finding the correct data after recent changes that reduced the number of styles in a project.  The nodeId attribute is also included when exporting a project to XHTML, which is undesirable according to Ken Zook.  I fixed this by added an IsXhtmlExport property to GeneratorSettings and passing GeneratorSettings to all of the methods in LcmXhtmlGenerator that wrote a nodeId attribute.  I also added a WriteNodeId method which contains the logic for deciding whether a nodeId attribute should be written out.
I believe that the IsXhtmlExport property is only set when exporting XHTML, but I don't know how to test whether the Dictionary Configuration option is still working …
=> LT-22039: xhtml has new nodeId attribute

Src/FwCoreDlgs/FwNewLangProjectModel.cs
There is an "en" writing system created implicitly by the 7th argument of CreateNewLangProj.  To avoid duplicates, we remove any "en" writing systems from the 8th argument to CreateNewLangProj (n remainingAnalysisWss).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/285)
=> Fix LT-22057: Duplicate Analysis ws created for English

Src/LexText/Interlinear/FocusBoxController.ApproveAndMove.cs
oldWf.OccurrencesInTexts() crashes if oldWf.Cache is null.  In this case, oldWf is not really a wordform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/287)
=> Fix LT-22077: Crash in interlinear

Src/LexText/ParserCore/ParseFiler.cs, Src/LexText/ParserCore/ParserCoreTests/ParseWorkerTests.cs, Src/LexText/ParserCore/ParserScheduler.cs, Src/LexText/ParserCore/ParserWorker.cs
The crash occurred because ParserWorker.UpdateWordform tried to do a NonUndoableUnitOfWork to create a lower case wordform in its own thread, which crashed if the user happened to independently do something that broadcasted a PropChanged.  The fix was to postpone the NonUndoableUnitOfWork until the work was in the right thread (in ParserFiler).
I also renamed ParserWorker.UpdateWordform to ParserWorker.ParseAndUpdateWordform because it was too easy to confuse with ParserFiler.UpdateWordforms, and I simplified the branch that deals with lowercase wordforms by removing:
m_parseFiler.ProcessParse(wordform, priority, result, checkParser);
return true;
The branch now falls through to
return m_parseFiler.ProcessParse(wordform, priority, result, checkParser);
- - -
This change is [<img …
=> Fix LT-22079: Yellow Crash occurs while performing Reparse all words

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs, Src/xWorks/WordStylesGenerator.cs
Use textboxes for pictures, and use the picture options to set width and alignment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/284)
=> LT-22052: Use textboxes instead of textframes for pictures

Src/LexText/Interlinear/InterlinDocRootSiteBase.cs
This crashed because RootStText.Cache was null.  I assume that this is some sort of dummy RootStText.  I fixed this by avoiding processing it.  I'm not sure how RootStText.Cache became null.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/294)
=> Fix LT-22083: Crash occurs while importing interlinear into empty pane

Src/xWorks/RecordList.cs
I improved the guard.  This seemed to fix the problem.  In this case the caller allowed for a null response, but not all callers do.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/296)
=> Fix LT-22084: Crash while performing undo after deleting text

Src/xWorks/RecordList.cs
I improved the guard on SortObjects[index] to prevent a crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/298)
=> Fix LT-22086: Reversal Indexes crashes without any reversals

Src/xWorks/CssGenerator.cs, Src/xWorks/xWorksTests/ConfiguredLcmUsfmGeneratorTests.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorReversalTests.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs, Src/xWorks/xWorksTests/CssGeneratorTests.cs, Src/xWorks/xWorksTests/LcmJsonGeneratorTests.cs
The node names need to be unique but the first one does not need to contain an appended ‘-1’. By removing the ‘-1 we fix problems with Webonary code that is not expecting the appended ‘-1’.
Change-Id: I350d544b1786035a773f962c1058be9bb55258bf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/299)
=> Remove appended ‘-1’ from XHTML node names

Src/xWorks/RecordClerk.cs, Src/xWorks/RecordList.cs
The problem with https://jira.sil.org/browse/LT-22089 is that RecordList gets a PropChanged notification before InterestingTextList does, so RecordList.GetObjectSet returns the old value for InterestingTextList.   At Jason's suggestion, I fixed it by setting m_requestedLoadWhileSuppressed = true so that RecordList would get updated again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/301)
=> Fix LT-22089: Creating and undoing a text leads to confusion

Src/LexText/Interlinear/SandboxBase.cs
This is for https://jira.sil.org/browse/LT-22090.   It doesn't have an acceptance test, but it is pretty obvious from the stack trace what was causing the null reference pointer exception in IsLexicalPattern.  Mark Bean will have to verify that this fixes his problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/303)
=> Fix LT-22090: Green box crash in IsLexicalPattern

Src/xWorks/RecordList.cs
This fixes https://jira.sil.org/browse/LT-22092.  This bug was introduced when https://jira.sil.org/browse/LT-22089 got fixed.  I tightened things up so that both work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/306)
=> Fix LT-22092: Text & Words area is not functioning properly

Src/xWorks/RecordList.cs
This fixes https://jira.sil.org/browse/LT-22094 which was caused by the fix for https://jira.sil.org/browse/LT-22089.  https://jira.sil.org/browse/LT-22089 and https://jira.sil.org/browse/LT-22092 should be checked as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/309)
=> Fix LT-22094: the text entered always appears in a RLT direction

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs
We were checking the nodes DisplayLabel for “Subentries” but this can be different for “Minor Subentries”.  Changed the checks to use the class names instead of display labels.
This PR also prevents a possible situation where we could reference an incorrect style name.
Change-Id: I709d1ec18a6cb81eaa5070f184e2b7f8cb5faa58
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/308)
=> Word Export: LT-22051: Fix problem with “Minor Subentries”

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs, Src/xWorks/WordStylesGenerator.cs
- Removed unused paragraph styles.
- If there are multiple paragraph styles with the same DisplayNameBase, and they have identical properties, then redirect the references to use the same style and remove the duplicate.
Change-Id: Ie00017b6127b02ba2350076f2f2df41897178e7e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/310)
=> Word Export: LT-22051: Removed unused paragraph styles

Src/xWorks/LcmWordGenerator.cs
This change fixes some, but not all, of the before-after style problems identified in this bug.
Changed WriteProcessedCollection() so that it works similar to WriteProcessedObject(). If the fragment only contains a single run, then get the writing system from the run.
Change-Id: Ib5ea02c9907bf0cce7300d99427c33214c0c12bb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/313)
=> Word Export: LT-22099: Fix before-after style problems

Src/Common/Controls/XMLViews/ReallySimpleListChooser.cs
This fixes a bug in the code that I wrote to fix LT-21826:
https://github.com/sillsdev/FieldWorks/commit/da7cd68b733a0657a21ae06191aedc68d61c7015
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/315)
=> Fix LT-22103: Crash opening list chooser on multiple fields

Src/LexText/Lexicon/FLExBridgeListener.cs, Src/LexText/Morphology/MorphologyListener.cs
This issue was originally titled "Turn off vernacular spell-checking by default", but the title was changed when Beth found a mismatch between the state of vernacular spell-checking and what was happening.  I was not able to reproduce what Beth found, so she suggested that we turn off vernacular spell-checking by default and if she sees the problem again she would report it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/324)
=> Fix LT-22065: Turn off vernacular spell-checking by default

Src/xWorks/ConfigurableDictionaryNode.cs, Src/xWorks/DictionaryConfigurationController.cs, Src/xWorks/DictionaryConfigurationDlg.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/XhtmlDocView.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs, Src/xWorks/xWorksTests/DictionaryConfigurationControllerTests.cs, Src/xWorks/xWorksTests/LcmJsonGeneratorTests.cs
* Stop using hashcode and use a customized node path id generating algorithm
* Also update an obsolete variable name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/320)
=> Fix LT-22036: Change node identification algorithm

Src/xWorks/LcmWordGenerator.cs, Src/xWorks/WordStyleCollection.cs
We want to use the specific writing system to get the style properties for before/after/between content, but we don’t typically want to use the specific
ws to determine if the rtl flag should be set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/328)
=> Word Export: LT-22112: Fix RTL gram. info in wrong place

DistFiles/Language Explorer/Configuration/Parts/Morphology.fwlayout
This fixes https://jira.sil.org/browse/LT-21206 (along with the latest version of liblcm).
Should the label for FsFeatDefn at line 276 also be changed?
How about the label for FsComplexFeature at line 363?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/332)
=> Fix LT-21206: Features label misleading

Src/views/VwSimpleBoxes.cpp
Use darker color for gray divider line between elements in Lexicon Entry edit display (e.g. between reversals or complex forms).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/334)
=> LT-21952: Darken divider line

DistFiles/Language Explorer/Configuration/Parts/Morphology.fwlayout, Src/LexText/LexTextDll/HelpTopicPaths.resx
I changed the label for Complex Features to "Display label".
I updated the documentation for Display label to use the new documentation that Marlon wrote.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/337)
=> LT-21206: Update documentation for Display label

Src/xWorks/FwXWindow.cs
I added code to write changes out when FieldWorks loses the focus.  This avoids a problem that Ron Lockwood was running into where the changes that he had just made in FieldWorks weren't visible to FlexTrans because he didn't let FieldWorks idle for a full second before switching back to FlexTrans.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/339)
=> Fix LT-21729: Reduce the delay in writing cached data

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/WordStyleCollection.cs
Add the list name to the style names used for items on the list.  This was done to make it easier for users to identify where the style for a list item is used.
Change-Id: I637520347dc3f0994a0c5e8a06aee1d0298f20cf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/342)
=> Word Export: LT-22113: Add the list name to style names

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/ILcmContentGenerator.cs, Src/xWorks/LcmJsonGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs
Fixed yellow highlighting in the Configure Dictionary dialog for Lexical Relations and Grammatical Info.
Change-Id: Ibbd63d6cf8df2023cd9597bcdb3d8a09a3107a69
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/346)
=> LT-22091: Fix Dictionary Configuration yellow highlighting

Src/Common/Controls/XMLViews/MatchingObjectsBrowser.cs, Src/Common/FieldWorks/FieldWorks.cs, Src/LexText/LexTextControls/LinkAllomorphDlg.cs
Double-clicking on an abstract morpheme no longer caused a crash, but the Choose Allomorph dialog box wasn't displaying any morphemes after the first search.  This was because the French DefaultCollation was being changed after the first search by RecordSorter, and then the DefaultCollation no longer matched the data in the searcher.  The DefaultCollation was being changed from a standard collation to the system collation to a void a bug when a standard collation doesn't have any rules.  I copied the code to change the DefaultCollation to the initialization code in FieldWorks.EnsureDefaultCollationsPresent to avoid this problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix LT-21461: Problems with Choose Allomorph dialog box

Build/mkall.targets, Build/nuget-common/packages.config
This incorporates the latest liblcm, which fixes https://jira.sil.org/browse/LT-22121 and https://jira.sil.org/browse/LT-22110.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/350)
=> Fix LT-22121: Analysis guesser should not guess ras for rAs

Src/xWorks/FwXWindow.cs
This undoes https://github.com/sillsdev/FieldWorks/commit/f01203ae64017542b2348b29eb84a598de19e7fd, which didn't fix https://jira.sil.org/browse/LT-21729 according to Sara and which caused https://jira.sil.org/browse/LT-22128 and https://jira.sil.org/browse/LT-22129.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/352)
=> Fix LT-22129: Crash when clicking the Insert Affix Template

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/CssGenerator.cs, Src/xWorks/LcmWordGenerator.cs, Src/xWorks/LcmXhtmlGenerator.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs, Src/xWorks/xWorksTests/LcmJsonGeneratorTests.cs
WS to use for picture copyright is already specified as an argument in AddProperty and used in the Word Export. Add handling in the xhtml generator to add a lang element to the property.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/343)
=> LT-22048 Make picture copyright use analysis WS style

DistFiles/Language Explorer/Configuration/Grammar/DataTreeInclude.xml
This fixes [LT-22132].  It should be safe to add to release 9.2 since it doesn't change any code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/355)
=> Fix LT-22132: Allow ability to reorder Affix Templates

Src/xWorks/ConfiguredLcmGenerator.cs, Src/xWorks/xWorksTests/ConfiguredXHTMLGeneratorTests.cs, Src/xWorks/xWorksTests/LcmJsonGeneratorTests.cs
Regardless of whether we are generating an entry for viewing in Flex or for exporting, use the same rules to determine if links to other entries should be created. If the target entry is not displayed then don’t generate a link (Guid).
Change-Id: I3cc000e3d5cace5f9041c92a0b6ad5255e3ac3ae
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/353)
=> LT-21996: Don’t create a link when there is no target

Src/FdoUi/InflectionFeatureEditor.cs
This seems like a safe fix for the stable release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/358)
=> Fix LT-15909: Crash selecting none of the above in inflection features

Src/Common/FieldWorks/FieldWorks.cs
After a thorough investigation of current LCM and palaso code
I can't find any places where SystemCollationDefinitions were
not Validated before being set in the DefaultCollation
There was that possibility here, but I couldn't reliably reproduce
the bug. This *may* address the root cause and it will prevent any
repeated crashing due to this type of writing system data error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/359)
=> Fix LT-22125: Clear out DefaultCollations that don't Validate

DistFiles/Language Explorer/Configuration/Lexicon/browseDialogColumns.xml
This should be safe for the stable release, although it may require a change to the help documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/360)
=> Fix LT-21907: Change Stem Name to Stem Allomorph Label

Src/LexText/Lexicon/ReversalListener.cs
In some situations the CurrentReversalWsId is not correct. Now we first try to get a ws from the SubComparer (if it is a WritingSystemComparer). This looks like the same place that the Sorter gets the ws.
Note: This change also fixes a similar problem with the reversal sort order in Word Export.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/363)
=> LT-21766: Fix Reversal Sort Order in Webonary

Src/LexText/Interlinear/InterlinVc.cs
This fixes https://jira.sil.org/browse/LT-22146.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/366)
=> Fix LT-22146: Darken guess colors in interlinear text display

Src/LexText/ParserCore/FwXmlTraceManager.cs
It was possible to get a null value for fs.Head().  This fixes it.
Change-Id: If2769369514d415054687db2285b3c4801c23b2f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/372)
=> Fix LT-22158: error in Try a Word tracing with Hermit Crab

DistFiles/Language Explorer/Configuration/Main.xml, DistFiles/Language Explorer/Configuration/Words/areaConfiguration.xml, Src/LexText/Interlinear/ChooseAnalysisHandler.cs, Src/LexText/Interlinear/ITextStrings.Designer.cs, Src/LexText/Interlinear/ITextStrings.resx, Src/LexText/Interlinear/InterlinMaster.cs, Src/LexText/Interlinear/InterlinVc.cs, Src/LexText/Interlinear/SandboxBase.ComboHandlers.cs, Src/xWorks/RecordClerk.cs, Src/xWorks/xWorksStrings.Designer.cs, Src/xWorks/xWorksStrings.resx
I made changes to https://jira.sil.org/browse/LT-21945 requested by Beth:
- Replaced "Parsing" tab with "Paring Dev" status bar.
- Renamed "Text Analysis" to "Text Glossing"
I also replaced ParsingMode with ParsingDevMode to make names more consistent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/375)
=> Fix LT-21945: Interlinear mode changes requested by Beth

Src/LexText/Interlinear/InterlinMaster.cs
Added a call to SaveBookmark so that Clerk.JumpToIndex would focus the right object.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/378)
=> Fix LT-22162: Sandbox focus shifts when switching interlinear mode

Src/LexText/Interlinear/BIRDInterlinearImporter.cs
This fixes https://jira.sil.org/browse/LT-22153.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/382)
=> Fix LT-22153: Analyses marked as "guess" in .flextext file

Src/GenerateHCConfig/ConsoleLogger.cs, Src/LexText/ParserCore/HCLoader.cs, Src/LexText/ParserCore/HCParser.cs, Src/LexText/ParserCore/IHCLoadErrorLogger.cs, Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs, Src/Transforms/Presentation/FormatCommon.xsl
One project got a Yellow Crash box with Hermit Crab.  It was due to a mismatch between a partial reduplication pattern and its environment (using the XAmple-style pattern where natural classes are indexed).  In this case, the form was
[C^1][V^1][C^2][C^3]
and the environment was
/[C^1][V^1][C^2]h_
Either the form needed to not have [C^3] or the environment needed to have an instance of [C^3].
The fix is to have HCLoader.cs check for any missing piece and ignore it.  The fix also creates an error message which shows in Try a Word.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/381)
=> LT-18767 yellow box crash in HC for bad XAmple-style reduplication

Src/LexText/Morphology/InflAffixTemplateControl.cs
This fixes https://jira.sil.org/browse/LT-22181, which was introduced by the change implementing https://jira.sil.org/browse/LT-826.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/392)
=> Fix LT-22181: Crash when clicking the stem dropdown

DistFiles/Language Explorer/Configuration/Words/areaConfiguration.xml
This fixes https://jira.sil.org/browse/LT-22192.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/407)
=> Fix LT-22192: Put default menu item first in Interlinear Mode menu

Src/LexText/Interlinear/FocusBoxController.cs, Src/LexText/Interlinear/SandboxBase.cs
This fixes https://jira.sil.org/browse/LT-22193.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/413)
=> Fix LT-22193: Change in Yellow Bar behavior in Interlinear Texts

Src/Common/Controls/DetailControls/StringSlice.cs, Src/Common/SimpleRootSite/SimpleRootSite.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/415)
=> Fix LT-22145: Make non-multilingual string slices default to 1st analysis

Src/LexText/Interlinear/SandboxBase.cs
This fixes https://jira.sil.org/browse/LT-22235.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/421)
=> Fix LT-22235: Guess Word Gloss should use Root gloss

Src/LexText/ParserCore/FwXmlTraceManager.cs
This fixes https://jira.sil.org/browse/LT-22204.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/429)
=> Fix LT-22204: Phonological rule output not written correctly

Src/Common/Controls/DetailControls/Slice.cs
This fixes the issues noted in a comment by Jaswanth in https://jira.sil.org/browse/LT-3356.  Using Indent was an imperfect proxy for whether one slice was embedded in another.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/440)
=> Fix issues noted when testing LT-3356

DistFiles/Language Explorer/Configuration/Parts/MorphologyParts.xml
This fixes https://jira.sil.org/browse/LT-22171.  The Phoneme/Features column was disappearing because it was invalid: there isn't a "Segments" field in PhNaturalClass.  It is in PhNCSegments instead, which is a subclass of PhNaturalClass.   Adding a new part made it valid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/444)
=> Fix LT-22271: Phonemes/Features column disappears from table

Build/mkall.targets, Build/nuget-common/packages.config
This fixes https://jira.sil.org/browse/LT-22227 (fixed in liblcm).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/451)
=> Fix LT-22227: Keep affix ordering when duplicating a slot

Src/xWorks/DTMenuHandler.cs
This fixes https://jira.sil.org/browse/LT-22240.  I tried broadcasting "SlotMoved", but InflAffixTemplateControl isn't able to receive messages unless it is being edited.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/452)
=> Fix LT-22240: Refresh template after moving affix slot

Src/xWorks/CssGenerator.cs
GenerateCssFromWsOptions() was only generating rules for one writing system. Changed this to generate rules for all enabled writing systems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/454)
=> LT-22185: XHTML: Fix style when there are multiple ws

Build/mkall.targets, Build/nuget-common/packages.config
The fix for this is mainly in SIL.Machine, version 3.7.4.
This pull request is to update the nuget versions used by Flex for SIL.Machine and SIL. Machine.Morphology.HermitCrab,
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/456)
=> LT-22190: HC can use wrong categories

Src/LexText/ParserUI/TryAWordDlg.cs, Src/LexText/ParserUI/WebPageInteractor.cs, Src/Transforms/Presentation/FormatHCTrace.xsl, Src/Transforms/Presentation/FormatXAmpleParse.xsl, Src/Transforms/Presentation/FormatXAmpleTrace.xsl, Src/Transforms/Presentation/FormatXAmpleWordGrammarDebuggerResult.xsl, Src/Transforms/Presentation/JSFunctions.xsl, Src/Transforms/Presentation/XLingPap1.xsl, Src/xWorks/GeneratedHtmlViewer.cs
This adds a Find dialog to the grammar sketch and to the various outputs of Try a Word.
This adds javascript (and a little CSS) to each web page produced by the various transforms used.  The javascript and CSS code are in the new JSFunctions.xsl file.
The Find dialog is launched whenever the use keys CTL-F or right-clicks and chooses the one Find option.  It allows the user to match by case and shows the number of matches.  The current match is highlighted in orange; all other matches ae highlighted in yellow.  It tries to center the current match in the window.  It automatically wraps when the last/fist item is found and the user asks to find the next/previous match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> LT-22182 Add "Find" to sketch and Try a Word

Src/LexText/Interlinear/FocusBoxController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/FieldWorks/484)
=> Fix LT-22295: Don't crash if MakeDefaultSelection is called early
